CREATE DATABASE "BarnDB"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'C'
    LC_CTYPE = 'C'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;


CREATE ROLE scarecrow WITH LOGIN SUPERUSER PASSWORD '1234';

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";